export const suggestBriefFieldsSchema = {
  name: "suggest_brief_fields_response",
  schema: {
    type: "object",
    additionalProperties: false,
    required: ["success", "suggestions"],
    properties: {
      success: {
        type: "boolean",
      },
      suggestions: {
        type: "object",
        additionalProperties: false,
        required: [
          "topicContext",
          "contentLength",
          "primaryKeyword",
          "secondaryKeywords",
          "location",
          "internalLinks",
          "competitorLinks",
          "seoNotes",
          "targetAudience",
          "audienceKnowledgeLevel",
          "contentGoal",
          "userStage",
          "clientOffer",
          "toneOfVoice",
          "restrictions",
          "clientNotes",
          "suggestionReasoning",
        ],
        properties: {
          topicContext: { type: "string" },
          contentLength: { type: "string" },
          primaryKeyword: { type: "string" },
          secondaryKeywords: { type: "string" },
          location: { type: "string" },
          internalLinks: { type: "string" },
          competitorLinks: { type: "string" },
          seoNotes: { type: "string" },
          targetAudience: { type: "string" },
          audienceKnowledgeLevel: { type: "string" },
          contentGoal: { type: "string" },
          userStage: { type: "string" },
          clientOffer: { type: "string" },
          toneOfVoice: { type: "string" },
          restrictions: { type: "string" },
          clientNotes: { type: "string" },
          suggestionReasoning: {
            type: "object",
            additionalProperties: false,
            required: [
              "userIntent",
              "keywordLogic",
              "contentQualityNotes",
              "aiVisibilityNotes",
            ],
            properties: {
              userIntent: { type: "string" },
              keywordLogic: { type: "string" },
              contentQualityNotes: {
                type: "array",
                items: { type: "string" },
              },
              aiVisibilityNotes: {
                type: "array",
                items: { type: "string" },
              },
            },
          },
        },
      },
    },
  },
  strict: true,
} as const;